version: "3.7"

services:
  ##########################################################################
  ######                       TOOL SERVER                           #######
  ##########################################################################
  validly-server:
    ports:
      - 8000:8000
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: >
      /bin/sh -c "
      uvicorn app.main:app --reload --host 0.0.0.0;
      "
    env_file:
      - .env
    networks:
      - validly

networks:
  validly: